// for administors
// add article actions
export const SAVE_ARTICLE_REQUEST = 'SAVE_ARTICLE_REQUEST'
export const SAVE_ARTICLE_SUCCESS = 'SAVE_ARTICLE_SUCCESS'
export const SAVE_ARTICLE_FAILURE = 'SAVE_ARTICLE_FAILURE'

// delete article actions
export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE'

// edit article actions
export const EDIT_ARTICLE_REQUEST = 'EDIT_ARTICLE_REQUEST'
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS'
export const EDIT_ARTICLE_FAILURE = 'EDIT_ARTICLE_FAILURE'

export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'

// for users
// todo FETCH_ARTICLES_REQUEST / FETCH_ARTICLES_SUCCESS / FETCH_ARTICLE_FAILURE
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES'
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES'

export const READ_ARTICLE = 'READ_ARTICLE'
export const COMMENT = 'COMMENT'
export const SEARCH = 'SEARCH'

export const RATING_REQUEST = 'RATING_REQUEST'
export const RATING_SUCCESS = 'RATING_SUCCESS'
export const RATING_FAILURE = 'RATING_FAILURE'