// for administors
export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST'
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS'
export const ADD_ARTICLE_FAILURE = 'ADD_ARTICLE_FAILURE'

export const REQUEST_DELETE_ARTICLE = 'REQUEST_DELETE_ARTICLE'
export const REQUEST_EDIT_ARTICLE = 'REQUEST_EDIT_ARTICLE'

export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'

// for users
// todo FETCH_ARTICLES_REQUEST / FETCH_ARTICLES_SUCCESS / FETCH_ARTICLE_FAILURE
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES'
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES'

export const READ_ARTICLE = 'READ_ARTICLE'
export const RATING = 'RATING'
export const COMMENT = 'COMMENT'
export const SEARCH = 'SEARCH'
export const SORT_BY_TITLE = 'SORT_BY_TITLE'
export const SORT_BY_DATE = 'SORT_BY_DATE'
export const SORT_BY_TRAFFIC = 'SORT_BY_TRAFFIC'