// for administors
export const CREATE_ARTICLE = 'CREATE_ARTICLE'
export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST'
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS'
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE'

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE'

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'
export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST'
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS'
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE'


export const CREATE_USER = 'CREATE_USER'
export const DELETE_USER = 'DELETE_USER'

// for users
// todo FETCH_ARTICLES_REQUEST / FETCH_ARTICLES_SUCCESS / FETCH_ARTICLE_FAILURE
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES'
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES'

export const READ_ARTICLE = 'READ_ARTICLE'
export const COMMENT = 'COMMENT'

export const SEARCH = 'SEARCH'
export const SEARCH_TAG = 'SEARCH_TAG'

export const RATING_REQUEST = 'RATING_REQUEST'
export const RATING_SUCCESS = 'RATING_SUCCESS'
export const RATING_FAILURE = 'RATING_FAILURE'

export const REQUEST_DASHBOARD = 'REQUEST_DASHBOARD'
export const RECEIVE_DASHBOARD = 'RECEIVE_DASHBOARD'